ChalupaHaj/Controllers/CsController.cs
using Microsoft.AspNetCore.Mvc;
using ChalupaHaj.Models;
using ChalupaHaj.Data;
using System.Net.Mail;
using System.Text;

namespace ChalupaHaj.Controllers
{
    //Main controller - returns views with czech language
    public class CsController : Controller
    {
        //creates database context
        private readonly ApplicationDbContext _context;

        public CsController(ApplicationDbContext context)
        {
            _context = context;

        }


        //returns home page
        public IActionResult Index()
        {
            return View();
        }
       

        //returns page with galery
        public IActionResult Galerie()
        {
            return View();
        }


        //returns page with price list
        public IActionResult Cenik()
        {
            return View();
        }


        //returns page with contact form
        public IActionResult Kontakt()
        {
            return View();
        }


        //CONTACT US FORM
        //on post saves contact us form to the database and sends it via email
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Email,Phone,Message")] Form contactUsForm)
        {
            //check if form inputs are valid
            if (ModelState.IsValid)
            {
                //saves form to database
                _context.Add(contactUsForm);
                await _context.SaveChangesAsync();


                //creates new mail with sender and reciever
                string to = "cernyvo4@chalupa-haj.cz";
                string from = "cernyvo4@chalupa-haj.cz";
                MailMessage mail = new MailMessage(from, to);


                //creates mailbody
                string mailbody = "<h1>Chalupa Háj | Nový dotaz</h1><br><hr><br>" + contactUsForm.Message + "<br><br>" + "<hr><br>" + contactUsForm.Name + " " + contactUsForm.Surname + "<br>" + contactUsForm.Email + "<br>" + contactUsForm.Phone;
                mail.Subject = "Chalupa Háj | Nový dotaz";
                mail.Body = mailbody;
                mail.BodyEncoding = Encoding.UTF8;


                //smpt server settings
                mail.IsBodyHtml = true;
                SmtpClient client = new SmtpClient("smtp.forpsi.com", 587);
                client.EnableSsl = true;
                client.UseDefaultCredentials = false;
                System.Net.NetworkCredential basicCredential1 = new
                System.Net.NetworkCredential("cernyvo4@chalupa-haj.cz", "Apollo11!");
                client.Credentials = basicCredential1;


                //tries to send email
                try
                {
                    client.Send(mail);
                    ViewBag.SendedFormType = "Děkujeme! Vaše zpráva byla úspěšně odeslána.";
                    return View("Odeslano");
                }


                //throws exception if send was unsuccessfull
                catch (Exception ex)
                {
                    throw ex;
                }

            }
            return View("Index");
        }


        //returns page with reservation form
        public IActionResult Rezervace()
        {
            return View();
        }


        //RESERVATION FORM
        //on post reservation form to the database and sends it to email
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Rezervace([Bind("Id,Name,Surname,Email,Phone,Arrival,Departure,NumberOfPersons,Message")] ReservationForm reservationForm)
        {
            if (ModelState.IsValid)
            {
                //saves form to database
                _context.Add(reservationForm);
                await _context.SaveChangesAsync();


                //creates new mail with sender and reciever
                string to = "cernyvo4@chalupa-haj.cz";
                string from = "cernyvo4@chalupa-haj.cz";
                MailMessage mail = new MailMessage(from, to);


                //creates mail body
                string mailbody = "<h1>Chalupa Háj | Nová rezervace</h1><br><hr><br>" + reservationForm.Name + " " + reservationForm.Surname + "<br>" + reservationForm.Email + "<br>" + reservationForm.Phone + "<br><br><hr><br>Datum příjezdu: " + reservationForm.Arrival + "<br>Datum odjezdu: " + reservationForm.Departure + "<br>Počet osob: " + reservationForm.NumberOfPersons + "<br><br><hr><br>" + reservationForm.Message;
                mail.Subject = "Chalupa Háj | Nová rezervace";
                mail.Body = mailbody;
                mail.BodyEncoding = Encoding.UTF8;


                //smpt server settings
                mail.IsBodyHtml = true;
                SmtpClient client = new SmtpClient("smtp.forpsi.com", 587);
                client.EnableSsl = true;
                client.UseDefaultCredentials = false;
                System.Net.NetworkCredential basicCredential1 = new
                System.Net.NetworkCredential("cernyvo4@chalupa-haj.cz", "Apollo11!");
                client.Credentials = basicCredential1;


                //tries to send email
                try
                {
                    client.Send(mail);
                    ViewBag.SendedFormType = "Děkujeme! Vaše nezávazná poptávka byla úspěšna přijata. Brzy Vás kontaktujeme s potvrzením a cenovou kalkulací.";
                    return View("Odeslano");
                }


                //throws exception if send was unsuccessfull
                catch (Exception ex)
                {
                    throw ex;
                }

            }

            //returns page after successfully sended
            return View("Odeslano");
        }     
    }
}

ChalupaHaj/Views/Shared/Components/ContactUsForm/ContactUsFormViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChalupaHaj.Data;
using ChalupaHaj.Models;
using Microsoft.EntityFrameworkCore.Storage;
using ChalupaHaj.Controllers;


namespace ChalupaHaj.Views.Shared.Components.ContactUsForm
{
    public class ContactUsFormViewComponent : ViewComponent
    {


        //creates database context
        private readonly ApplicationDbContext _context;


        //creates instansce of database context - to be used, when returning view
        public ContactUsFormViewComponent(ApplicationDbContext context)
        {
            _context = context;
            
        }


        //input - user created form, sends to database and return view 
        public async Task<IViewComponentResult> InvokeAsync([Bind("Id,Name,Surname,Email,Phone,Message")] Form contactUsForm)
        {      
            return await Task.FromResult((IViewComponentResult)View());
        }


    }
}

ChalupaHaj/Views/Shared/Components/News/NewsViewComponent.cs
using ChalupaHaj.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace ChalupaHaj.Views.Shared.Components.News
{
    public class NewsViewComponent : ViewComponent
    {


        //creates database context
        private readonly ApplicationDbContext _ctx;


        //creates instansce of database context - to be used, when returning view
        public NewsViewComponent(ApplicationDbContext ctx)
        {
            _ctx = ctx;
        }


        //returns view component with news articles
        public async Task<IViewComponentResult> InvokeAsync()
        {

            var news = await _ctx.News.ToListAsync();
            return View(news);
            
        }

      
    }
}

ChalupaHaj/Views/Shared/Components/Reservation/ReservationViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChalupaHaj.Data;
using ChalupaHaj.Models;
using Microsoft.EntityFrameworkCore.Storage;
using ChalupaHaj.Controllers;

namespace ChalupaHaj.Views.Shared.Components.ReservationForms
{
    public class ReservationViewComponent : ViewComponent
    {
        //creates database context
        private readonly ApplicationDbContext _context;


        //creates instansce of database context - to be used, when returning view
        public ReservationViewComponent(ApplicationDbContext context)
        {
            _context = context;

        }


        //input - user created form, sends to database and return view 
        public async Task<IViewComponentResult> InvokeAsync([Bind("Id,Name,Surname,Email,Phone,Arrival,Departure,NumberOfPersons,Message")] ReservationForm reservationForm)
        {
            return await Task.FromResult((IViewComponentResult)View());
        }


    }
}

ChalupaHaj/Views/Cs/Index.cshtml
@section css {
    <link href="@Url.Content("~/css/cz/index.css")" rel="stylesheet">
}

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Chalupa Háj | Úvod";
    
}


<!--Content-->


<!--Main content-->
<div class="main">


    <!--Button reservation-->
    <div class="greyBox">
        <a asp-controller="cs" asp-action="rezervace">Rezervace</a>
    </div>


    <!--Main image-->
    <img src="~/images/chalupa1.jpg" alt="Chalupa Háj">


    <!--Main article-->
    <div class="greenBox">
        <p>
            Přijměte prosím naše pozvání do příjemných a útulných prostor naší chalupy. Ať k nám zavítáte na
            jednu či více nocí, věříme, že se u nás budete cítit jako doma. Nabízíme Vám pohodlně vybavené
            pokoje, společenskou místnost s kulečníkem, krbem, barem a výčepním zařízením a s dětským koutkem.
        </p>
    </div>


</div>


<!--Renders view component - news content-->


@await Component.InvokeAsync("News")


<!--Galery Content-->
<div class="galery">


    <!--Galery header-->
    <div class="greyBox">
        <a asp-controller="cs" asp-action="galerie">Galerie</a>
    </div>


    <!--Galery container-->
    <div class="galery-container">

        <!--exterior-->
        <img src="~/images/exterier/11.jpg" alt="Chalupa Háj">

        <!--interior-->
        <img src="~/images/interier/09.jpeg" alt="Chalupa Háj">

        <!--surroundings-->
        <img src="~/images/chalupa3.jpg" alt="Chalupa Háj">

    </div>

</div>


<!--Contact content-->
<div class="contact">


    <!--Contact header-->
    <div class="greyBox">
        <a asp-controller="Cs" asp-action="kontakt">Kontakt</a>
    </div>


    <!--Render view component with contact us form-->
    @await Component.InvokeAsync("ContactUsForm")


    <!--map with location from google maps-->
    <div id="map"></div>

</div>

ChalupaHaj/Views/Cs/kontakt.cshtml
@section css {
    <link href="@Url.Content("~/css/cz/kontakt.css")" rel="stylesheet" />
}

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Chalupa Háj | Kontakt";

}


<div class="greyBox">
    <h2>Kontakt</h2>
</div>

<div class="greenBox">


    <div>
        <h3>Chalupa Háj ***</h3>
        <address>Háj 17, 356 01 Jindřichovice</address><address>Česká republika</address>
    </div>
    <hr>


    <div>
        <h3>Kontakt</h3>
        <a href="mailto: info@chalupa-haj.cz">info@chalupa-haj.cz</a><br />
        <a href="tel: +420721046446">+420 721 046 446</a><br />
        <a href="tel: +420728979036">+420 728 979 036</a><br />
    </div>
</div>

<!--Render view component with contact us form-->
@await Component.InvokeAsync("ContactUsForm")

    
<div id="map"></div>

ChalupaHaj/Views/Cs/rezervace.cshtml
@section css {
    <link href="@Url.Content("~/css/cz/rezervace.css")" rel="stylesheet" />
}

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Chalupa Háj | Rezervace";

}

<div class="greyBox">
    <h2>REZERVACE</h2>
</div>

@await Component.InvokeAsync("Reservation")

<div class="obsazenost">
    <iframe src="https://obsazenost.e-chalupy.cz/kalendar.php?id=1026&pocetMesicu=12&velikost=3&legenda=ne&vybraneMesice=&naStred=ano&ctvrtleti=ne&stin=ne&jazyk=cz&jednotky=ano&idJednotky=0&vypisJednotky=ne&souhrnny=&pozadi=ffffff&kalendarText=000000&kalendarPozadi=ffffff&ramecek=dddddd&mesicText=555555&mesicPozadi=dddddd&dnyText=008000&dnyPozadia=ffffff&obsazenoText=222222&obsazenoPozadi=f74848&volnoText=222222&volnoPozadi=67cf67&castecneText=222222&castecnePozadi=489ce0&neaktivniDnyText=bbbbbb&neaktivniDnyPozadi=ffffff&legendaText=000000&fontFamily=Open%20Sans&extCss=" height="460px" width="100%" frameborder="0" id="echalupy-kalendar"></iframe>
</div>